name: ai_env
channels:
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pip:
    - flask==2.3.2
    - flask_sqlalchemy==3.0.3
    - python-dotenv==1.0.0
    - torch==1.8.1
    - torchvision==0.9.1